name: Cache key
description: Generate cache key for ccache

inputs:
  build_type:
    description: Current build type (e.g. Release, Debug)
    required: true
  compiler:
    description: Compiler used for the build (e.g. gcc, clang)
    required: true
  code_coverage:
    description: Whether code coverage is on
    required: true
  sanitizers:
    description: Sanitizer to enable, read by the 'sanitizers' conan profile (e.g. 'address', 'thread', 'undefinedbehavior')
    required: true

outputs:
  build_identifier:
    description: Unique identifier for the build configuration
    value: ${{ steps.build_identifier.outputs.build_identifier }}
  key:
    description: Generated cache key for ccache
    value: ${{ steps.build_identifier.outputs.build_identifier }}-${{ steps.git_common_ancestor.outputs.commit }}
  restore_keys:
    description: Cache restore keys for fallback
    value: ${{ steps.build_identifier.outputs.build_identifier }}

runs:
  using: composite
  steps:
    - name: Find common commit
      id: git_common_ancestor
      uses: ./.github/actions/git-common-ancestor

    - name: Build identifier
      id: build_identifier
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
        BUILD_TYPE: ${{ inputs.build_type }}
        COMPILER: ${{ inputs.compiler }}
        CODE_COVERAGE: ${{ inputs.code_coverage }}
        SANITIZERS: ${{ inputs.sanitizers }}
      run: |
        BUILD_IDENTIFIER="${RUNNER_OS}-${COMPILER}-${BUILD_TYPE}"
        if [ "${CODE_COVERAGE}" == "true" ]; then
          BUILD_IDENTIFIER+="-code_coverage"
        fi
        if [ -n "${SANITIZERS}" ]; then
          BUILD_IDENTIFIER+="-${SANITIZERS}"
        fi
        echo "build_identifier=${BUILD_IDENTIFIER}" >>"${GITHUB_OUTPUT}"
        echo "key=clio-ccache-${{ steps.build_identifier.outputs.build_identifier }}-develop" >>"${GITHUB_OUTPUT}"
