name: Generate code coverage report
description: Run tests, generate code coverage report and upload it to codecov.io

inputs:
  codecov_token:
    description: Codecov token for uploading coverage report
    required: true

runs:
  using: composite

  steps:
    - name: Run tests
      shell: bash
      run: |
        build/clio_tests

    - name: Run gcovr
      shell: bash
      run: |
        gcovr -e tests \
          -e src/data/cassandra \
          -e src/data/CassandraBackend.hpp \
          -e 'src/data/BackendFactory.*' \
          --xml build/coverage_report.xml -j8 --exclude-throw-branches

    - name: Upload coverage report
      if: ${{ hashFiles('build/coverage_report.xml') != '' }}
      uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
      with:
        files: build/coverage_report.xml
        fail_ci_if_error: false
        verbose: true
        token: ${{ inputs.codecov_token }}
