name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  run-hooks:
    uses: XRPLF/actions/.github/workflows/pre-commit.yml@8b19d3462e52cd8ea4d76b4c8d0f7533e7469c15
    with:
      runs_on: heavy
      container: '{ "image": "ghcr.io/xrplf/clio-pre-commit:14342e087ceb8b593027198bf9ef06a43833c696" }'
