name: Pre-commit auto-update

on:
  # every first day of the month
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
    branches: [release/*, develop]
    paths:
      - ".pre-commit-config.yaml"
  workflow_dispatch:

jobs:
  auto-update:
    uses: XRPLF/actions/.github/workflows/pre-commit-autoupdate.yml@ebfdb73e1a22763b44da3697484eb134d9441231
    with:
      sign_commit: true
      committer: "Clio CI <skuznetsov@ripple.com>"
      reviewers: "godexsoft,kuznetsss,PeterChen13579,mathbunnyru"
