name: Update CI docker image

on:
  pull_request:
    paths:
      - .github/workflows/update_docker_ci.yml

      - ".github/workflows/multiarch_image.yml"
      - ".github/actions/build_docker_image/**"

      - "docker/ci/**"
      - "docker/compilers/**"
      - "docker/tools/**"
  push:
    branches: [develop]
    paths:
      - .github/workflows/update_docker_ci.yml

      - ".github/workflows/multiarch_image.yml"
      - ".github/actions/build_docker_image/**"

      - "docker/ci/**"
      - "docker/compilers/**"
      - "docker/tools/**"
  workflow_dispatch:

concurrency:
  # Only matches runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  # We want to execute all builds sequentially in develop
  cancel-in-progress: false

env:
  CLANG_MAJOR_VERSION: 19
  GCC_MAJOR_VERSION: 12
  GCC_VERSION: 12.3.0

jobs:
  # https://github.com/orgs/community/discussions/26671
  vars:
    runs-on: ubuntu-latest
    outputs:
      GHCR_REPO: ${{ steps.set-ghcr-repo.outputs.GHCR_REPO }}
      GCC_MAJOR_VERSION: ${{ steps.set-vars.outputs.GCC_MAJOR_VERSION }}
      GCC_VERSION: ${{ steps.set-vars.outputs.GCC_VERSION }}
      CLANG_MAJOR_VERSION: ${{ steps.set-vars.outputs.CLANG_MAJOR_VERSION }}
    steps:
      - name: Set GHCR_REPO
        id: set-ghcr-repo
        run: |
          echo "GHCR_REPO=$(echo ghcr.io/${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_OUTPUT}

      - name: Set environment variables
        id: set-vars
        run: |
          echo "CLANG_MAJOR_VERSION=${{ env.CLANG_MAJOR_VERSION }}" >> $GITHUB_OUTPUT
          echo "GCC_MAJOR_VERSION=${{ env.GCC_MAJOR_VERSION }}" >> $GITHUB_OUTPUT
          echo "GCC_VERSION=${{ env.GCC_VERSION }}" >> $GITHUB_OUTPUT

  gcc:
    name: Build and push GCC docker image
    uses: ./.github/workflows/multiarch_image.yml
    needs: vars
    with:
      directory: docker/compilers/gcc
      image_name: clio-gcc
      tags: |
        latest
        ${{ needs.vars.outputs.GCC_MAJOR_VERSION }}
        ${{ needs.vars.outputs.GCC_VERSION }}
        ${{ github.sha }}
      build_args: |
        GCC_MAJOR_VERSION=${{ needs.vars.outputs.GCC_MAJOR_VERSION }}
        GCC_VERSION=${{ needs.vars.outputs.GCC_VERSION }}
      env: GHCR_REPO=${{ needs.vars.outputs.GHCR_REPO }}

  clang:
    name: Build and push Clang docker image
    uses: ./.github/workflows/multiarch_image.yml
    needs: vars
    with:
      directory: docker/compilers/clang
      image_name: clio-clang
      tags: |
        latest
        ${{ needs.vars.outputs.CLANG_MAJOR_VERSION }}
        ${{ github.sha }}
      build_args: |
        CLANG_MAJOR_VERSION=${{ needs.vars.outputs.CLANG_MAJOR_VERSION }}
      env: GHCR_REPO=${{ needs.vars.outputs.GHCR_REPO }}

  tools:
    name: Build and push tools docker image
    needs: [vars, gcc]
    uses: ./.github/workflows/multiarch_image.yml
    with:
      directory: docker/tools
      image_name: clio-tools
      tags: |
        latest
        ${{ github.sha }}
      build_args: |
        GHCR_REPO=${{ needs.vars.outputs.GHCR_REPO }}
        GCC_VERSION=${{ needs.vars.outputs.GCC_VERSION }}
      env: GHCR_REPO=${{ needs.vars.outputs.GHCR_REPO }}

  ci:
    name: Build and push CI docker image
    needs: [vars, gcc, clang, tools]
    uses: ./.github/workflows/multiarch_image.yml
    with:
      directory: docker/ci
      image_name: clio-ci
      tags: |
        latest
        gcc_${{ needs.vars.outputs.CLANG_MAJOR_VERSION }}_clang_${{ needs.vars.outputs.GCC_MAJOR_VERSION }}
        ${{ github.sha }}
      build_args: |
        GHCR_REPO=${{ needs.vars.outputs.GHCR_REPO }}
        CLANG_MAJOR_VERSION=${{ needs.vars.outputs.CLANG_MAJOR_VERSION }}
        GCC_VERSION=${{ needs.vars.outputs.GCC_VERSION }}
      env: GHCR_REPO=${{ needs.vars.outputs.GHCR_REPO }}
